# Generated by Django 5.0.3 on 2024-05-23 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funko_api', '0003_remove_user_funkos_user_funkos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('author', models.CharField(max_length=128)),
                ('editorial', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='funkos',
            field=models.ManyToManyField(blank=True, to='funko_api.funko'),
        ),
        migrations.AddField(
            model_name='user',
            name='libros',
            field=models.ManyToManyField(blank=True, to='funko_api.libro'),
        ),
    ]
