# Generated by Django 5.0.3 on 2024-06-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('number', models.IntegerField()),
                ('generation', models.CharField(choices=[('GEN1', 'Generation I'), ('GEN2', 'Generation II'), ('GEN3', 'Generation III'), ('GEN4', 'Generation IV'), ('GEN5', 'Generation V'), ('GEN6', 'Generation VI'), ('GEN7', 'Generation VII'), ('GEN8', 'Generation VIII')], max_length=4)),
                ('type', models.CharField(choices=[('NOR', 'Normal'), ('FIR', 'Fire'), ('WAT', 'Water'), ('ELE', 'Electric'), ('GRA', 'Grass'), ('ICE', 'Ice'), ('FIG', 'Fighting'), ('POI', 'Poison'), ('GRO', 'Ground'), ('FLY', 'Flying'), ('PSY', 'Psychic'), ('BUG', 'Bug'), ('ROC', 'Rock'), ('GHO', 'Ghost'), ('DRA', 'Dragon'), ('DAR', 'Dark'), ('STE', 'Steel'), ('FAI', 'Fairy')], max_length=4)),
                ('subtype', models.CharField(blank=True, choices=[('NOR', 'Normal'), ('FIR', 'Fire'), ('WAT', 'Water'), ('ELE', 'Electric'), ('GRA', 'Grass'), ('ICE', 'Ice'), ('FIG', 'Fighting'), ('POI', 'Poison'), ('GRO', 'Ground'), ('FLY', 'Flying'), ('PSY', 'Psychic'), ('BUG', 'Bug'), ('ROC', 'Rock'), ('GHO', 'Ghost'), ('DRA', 'Dragon'), ('DAR', 'Dark'), ('STE', 'Steel'), ('FAI', 'Fairy')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('region', models.CharField(choices=[('KAN', 'Kanto'), ('JOH', 'Johto'), ('HOE', 'Hoenn'), ('SIN', 'Sinnoh'), ('UNO', 'Unova'), ('KAL', 'Kalos'), ('ALO', 'Alola'), ('GAL', 'Galar')], max_length=3)),
                ('pokemons', models.ManyToManyField(blank=True, to='Pokemon.pokemon')),
            ],
        ),
    ]
